import { Theme } from '@emotion/react';
import { css } from '@emotion/react';

// types
import { TypographyStyle } from '@/app/types/common/theme';

const theme: Theme = {
  fontSize: {
    base: '16px',
  },

  breakpoint: {
    mobile: '@media (max-width: 780px)',
    mobileValue: '780px',
    tablet: '@media (max-width: 1280px)',
    tabletValue: '1280px',
  },

  color: {
    NEUTRAL: {
      White: '#ffffff',
      Basic: '#000000',
      Line: '#E4E8ED',
      Grey_90: '#2C3843',
      Grey_80: '#4C5967',
      Grey_70: '#68737E',
      Grey_60: '#8F99A3',
      Grey_50: '#ABB2BA',
      Grey_40: '#D5D9DD',
      Grey_30: '#E3E5E8',
      Grey_20: '#F0F2F5',
      Grey_10: '#F8F9FC',
      Neutral_300: '#E0E0E0',
      Neutral_800: '#424242',
    },
    ACCENT: {
      Red_100: '#f43',
      Blue_100: '#5E9BF6',
    },
    BRAND: {
      LOGO: '#711282',
      Purple_100: '#4C2E91',
      Purple_70: '#904BCC',
      Purple_50: '#A76FEA',
      Purple_30: '#CDA3FF',
      Secondary_100: '#9C94F4',
      Secondary_10: '#F3F3FF',
    },
    KAKAO: {
      bg: '#FEE500',
    },
    NAVER: {
      bg: '#03C75A',
    },
    BG: {
      BG_Gray: '#F4F4F5',
      BG_Cool: '#E8EBF4',
    },
    UI: {
      P_Text: '#A358B1',
      P_100: '#F9E6FF',
      C_Text: '#375DA4',
      C_100: '#EEF7FF',
      Y_Text: '#BF6B0A',
      Y_100: '#FFF2D7',
      G_100: '#DEF6EB',
      G_Text: '#2E9468',
      R_100: '#FFE9EE',
    },
  },

  typography: {
    Display_64_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '64px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '76.8px',
      letterSpacing: '-2.56px',
    },
    Display_64_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '64px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '76.8px',
      letterSpacing: '-2.56px',
    },
    Display_48_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '48px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '57.6px',
      letterSpacing: '-1.92px',
    },
    Heading_36_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '36px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '46.8px',
      letterSpacing: '-0.72px',
    },
    Heading_36_SemiBold: {
      fontFamily: 'Pretendard',
      fontSize: '36px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '46.8px',
      letterSpacing: '-0.72px',
    },
    Heading_36_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '36px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '46.8px',
      letterSpacing: '-0.72px',
    },
    Heading_32_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '32px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '41.6px',
      letterSpacing: '-0.64px',
    },
    Heading_32_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '32px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '41.6px',
      letterSpacing: '-0.64px',
    },
    Heading_28_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '28px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '36.4px',
      letterSpacing: '-0.56px',
    },
    Heading_28_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '28px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '36.4px',
      letterSpacing: '-0.56px',
    },
    Title_24_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '24px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '31.2px',
      letterSpacing: '-0.48px',
    },
    Title_24_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '24px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '31.2px',
      letterSpacing: '-0.48px',
    },
    Title_20_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '20px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '28px',
      letterSpacing: '-0.4px',
    },
    Title_20_SemiBold: {
      fontFamily: 'Pretendard',
      fontSize: '20px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '28px',
      letterSpacing: '-0.4px',
    },
    Title_20_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '20px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '28px',
      letterSpacing: '-0.4px',
    },
    Title_20_Regular: {
      fontFamily: 'Pretendard',
      fontSize: '20px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '28px',
      letterSpacing: '-0.4px',
    },
    New_Body_M_Regular: {
      fontFamily: 'Pretendard',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '150%',
      letterSpacing: '-0.32px',
    },
    Body_2_Bod: {
      fontFamily: 'Pretendard',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '22.4px',
      letterSpacing: '-0.32px',
    },
    Body_18_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '18px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '25.2px',
      letterSpacing: '-0.36px',
    },
    Body_18_SemiBold: {
      fontFamily: 'Pretendard',
      fontSize: '18px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '25.2px',
      letterSpacing: '-0.36px',
    },
    Body_18_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '18px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '25.2px',
      letterSpacing: '-0.36px',
    },
    Body_18_Regular: {
      fontFamily: 'Pretendard',
      fontSize: '18px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '25.2px',
      letterSpacing: '-0.36px',
    },
    Body_16_Bold: {
      fontFamily: 'Pretendard',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '22.4px',
      letterSpacing: '-0.32px',
    },
    Body_16_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '22.4px',
      letterSpacing: '-0.32px',
    },
    Body_16_Regular: {
      fontFamily: 'Pretendard',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '22.4px',
      letterSpacing: '-0.32px',
    },
    Label_1_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '14px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '19.6px',
      letterSpacing: '-0.28px',
    },
    Label_14_SemiBold: {
      fontFamily: 'Pretendard',
      fontSize: '14px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '19.6px',
      letterSpacing: '-0.14px',
    },
    Label_14_Medium: {
      fontFamily: 'Pretendard',
      fontSize: '14px',
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: '19.6px',
      letterSpacing: '-0.14px',
    },
    Label_14_Regular: {
      fontFamily: 'Pretendard',
      fontSize: '14px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '19.6px',
      letterSpacing: '-0.14px',
    },
    Caption_12_SemiBold: {
      fontFamily: 'Pretendard',
      fontSize: '12px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '16.8px',
      letterSpacing: '0',
    },
    Caption_12_Regular: {
      fontFamily: 'Pretendard',
      fontSize: '12px',
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: '16.8px',
      letterSpacing: '0',
    },
    Nanum_13_Bold: {
      fontFamily: 'NanumMyeongjo',
      fontSize: '13px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: '18.2px',
      letterSpacing: '-0.26px',
    },
  },
  applyTypography: (typographyStyle: TypographyStyle) => css`
    font-family: ${typographyStyle.fontFamily};
    font-size: ${typographyStyle.fontSize};
    font-style: ${typographyStyle.fontStyle};
    font-weight: ${typographyStyle.fontWeight};
    line-height: ${typographyStyle.lineHeight};
    letter-spacing: ${typographyStyle.letterSpacing};
  `,
  flex: {
    flexRow: {
      display: 'flex',
      flexDirection: 'row',
    },
    flexColumn: {
      display: 'flex',
      flexDirection: 'column',
    },
    flexRowCenter: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
    },
    flexRowCenterCenter: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    flexRowSpaceBetween: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },

    flexColumnCenter: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    flexColumnCenterCenter: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    flexColumnSpaceBetween: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  my: {
    examList: {
      container: 'ExamListContainer',
      content: 'ExamListContent',
      titleContainer: 'ExamListTitleContainer',
      title: 'ExamListTitle',
      titleIcon: 'ExamListTitleIcon',
    },
  },
};

export default theme;
